version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sistem-tiket:
    build: ./sistem-tiket
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/ticket_system
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mysql

  id-card-scanner:
    build: ./id-card-scanner
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  generate-pdf:
    build: ./generate-pdf
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    volumes:
      - shared-storage:/app/shared

  send-email:
    build: ./send-email
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    volumes:
      - shared-storage:/app/shared

  celery_card_scanner_worker:
    build: ./id-card-scanner
    command: celery -A app.celery worker --loglevel=info -Q card_scanner_worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq

  celery_generate_pdf_worker:
    build: ./generate-pdf
    command: celery -A generatePdf.celery worker --loglevel=info -Q generate_pdf_worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
    volumes:
      - shared-storage:/app/shared

  celery_send_email_worker:
    build: ./send-email
    command: celery -A sendEmail.celery worker --loglevel=info -Q send_email_worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
    volumes:
      - shared-storage:/app/shared

volumes:
  mysql_data:
  shared-storage:
